name: Update Changelog

on:
  pull_request:
  push:
    branches: [main]
    
jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '18'

      - name: Install Codex CLI
        run: npm install -g @openai/codex
        shell: bash  # Ensures consistency across platforms

      - name: Update changelog via Codex
        run: codex exec --full-auto "update CHANGELOG for next release"
        shell: bash  # Ensures command is parsed properly
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
