name: Run Tests and Upload Coverage

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  pull-requests: write  # Required to post PR comments with coverage summary

jobs:
  test-and-upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest coverage codecov

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage xml --ignore-errors


      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Only required for private repos
          files: coverage.xml
          flags: unittests  # Optional, helps identify test types
          name: codecov-report  # Optional report name
          fail_ci_if_error: true
