name: Update Changelog

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write  # Required to comment on PRs and update files

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '18'

      - name: Install Codex CLI
        run: npm install -g @openai/codex
        shell: bash

      - name: Generate and update CHANGELOG.md
        id: changelog
        run: |
          codex exec --full-auto "summarize the code changes for this pull request in changelog format and update the CHANGELOG.md file accordingly"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
        shell: bash

      - name: Commit and push updated CHANGELOG.md
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          if git diff --cached --quiet; then
            echo "No changes to CHANGELOG.md"
            exit 0
          fi
          git commit -m "chore: update CHANGELOG.md [automated]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read updated changelog
        id: read_changelog
        run: |
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          cat CHANGELOG.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash

      - name: Post changelog comment to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const output = `${{ steps.read_changelog.outputs.changelog }}`;
            const body = `### 📝 Updated CHANGELOG.md\n\n${output}`;
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
