name: Update Changelog

on:
  workflow_dispatch: # or push, pull_request, etc.

jobs:
  update-changelog:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '18'

      - name: Install Codex CLI
        run: npm install -g @openai/codex

      - name: Update changelog via Codex
        run: codex exec --full-auto "update CHANGELOG for next release"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
